sudo: false
dist: trusty
language: python
cache: pip

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev

env:
  matrix:
    - TOXENV=py
  global:
    - LOGNAME=travis

matrix:
  allow_failures:
    - python: 3.7-dev
  include:
    - python: 3.6
      env: TOXENV=flake8

install:
  - pip install tox

script:
  - dbus-launch --version
  - dbus-launch -- tox

after_script:
  - pip install codecov
  - codecov
