sudo: false
dist: trusty
language: python
cache: pip

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev

env:
  matrix:
    - TOXENV=py
  global:
    - LOGNAME=travis

matrix:
  allow_failures:
    - python: 3.7-dev
  include:
    - python: 3.6
      env: TOXENV=flake8

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y dbus

install:
  - pip install tox

script:
  - dbus-run-session --version
  - dbus-run-session -- tox

after_script:
  - pip install codecov
  - codecov
